baseURL: https://www.trevorromsdahl.org/
title: Trevor B. Romsdahl
theme: etch
languageCode: en-US
enableInlineShortcodes: yes
pygmentsCodeFences: yes
pygmentsUseClasses: yes
params:
  copyright: Copyright © 2022 Trevor B. Romsdahl
  dark: "off"
  description: Personal website of Trevor B. Romsdahl.
  highlight: yes
menu:
  main:
    - identifier: posts
      name: posts
      title: posts
      url: /
      weight: 10
    - identifier: categories
      name: categories
      title: categories
      url: /categories/
      weight: 11
    - identifier: tags
      name: tags
      title: tags
      url: /tags/
      weight: 12
    - identifier: CV
      name: CV
      title: CV
      url: /cv/
      weight: 15
    - identifier: about
      name: about
      title: about
      url: /about/
      weight: 20
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.mg$
  - \.utf8\.md$
permalinks:
  posts: /:year/:month/:day/:slug/
googleAnalytics: "G-NRW0DXEQ91"
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    ordered: yes
